### ISSUE TITLE
seems to be a small regression with respect to display names

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-facebook#10]
a new person (from the perspective of my HS) messages me, and the room name is set, but her display name is not set correctly.

**Comment by kfatehi** [comment]
it's also strange how all messages are tagged messages! maybe the default needs to not be [m] anymore.

**Comment by erdnaxeli** [comment]
About tags, maybe we should tags only the message from the puppetized user. My code was not very subtle and tags all the messages.
