### ISSUE TITLE
Photos and stickers aren't sent both ways

### ISSUE THREAD

**Issue by tfreedman** [matrix-hacks/matrix-puppet-facebook#5]
If someone sends a photo within Messenger, Matrix won't receive it. Likewise, if I attach a photo with Matrix, the other party won't receive it either.

**Comment by kfatehi** [comment]
in the imessage bridge i have a half-measure wherein the bridge sends a 'notice' (greyed out text) saying that there were X number of attachments in the message. having actual support would be great though and should be mostly implemented in the base (matrix-puppet-bridge)  and reused by all the bridges including imessage and facebook.
