### ISSUE TITLE
Known to disconnect and not reconnect or exit

### ISSUE THREAD

**Issue by kfatehi** [matrix-hacks/matrix-puppet-facebook#7]
This has happened to me a few times, after a few days or weeks of running. I need to track this bug down, it's somewhere in the facebook-chat-api node module. They may have an issue about it already on their bug tracker.

**Comment by tfreedman** [comment]
So I discovered that this also occurs if the internet connection drops out for a bit, which is a big problem.

**Comment by AndrewJDR** [comment]
facebook-chat-api was updated recently, so please try again with the latest version and reopen if it's still there.
